language: java
jdk:
  - openjdk8

brances:
  only:
    - master

before_install:
  - chmod +x mvnw

# Travic CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw clean install"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'kim125y@naver.com'
