spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    #url: jdbc:h2:mem:jpashop
    #url: jdbc:h2:tcp://db-server:1521/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  logback:
    rollingpolicy:
      clean-history-on-start: