spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/springboot
    username: postgres
    password: ng1029

  h2:
    console:
      enabled: true

  profiles:
    active: local
    include: credentials

  servlet:
    multipart:
      max-file- size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  logback:
    rollingpolicy:
      clean-history-on-start:

server:
  port: 7070

upload:
  path: C:\Users\김시호\Desktop\app이미지


cloud:
  aws:
    s3:
      bucket: app-product-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true