spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/springboot
    username: postgres
    password: ng1029

  h2:
    console:
      enabled: true

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  logback:
    rollingpolicy:
      clean-history-on-start:

server:
  port: 7070